export interface Product {
  id: string;
  name: string;
  brand: string;
  manufacturer: string;
  categories: string[];
  countryOfOrigin: string;
  description: string;
  packContents: string[];
  ingredients: string[];
  benefits: string[];
  treatmentAreas: string[];
  image: string;
  price?: string;
  lidocaine: boolean;
  volume: string;
}

export const ALL_BRANDS = [
  'Aessoa', 'Aliaxin', 'Aquashine', 'Belotero', 'E.p.t.q', 'Fillmed',
  'HarmonyCa', 'HYAcorp', 'Innoaesthetics', 'Juvederm', 'Kairax',
  'Lumifil', 'Mesoestetic', 'Neauvia', 'Neuramis', 'Nucleofill',
  'Profhilo', 'Restylane', 'Revanesse', 'Revofil', 'Revolax',
  'Saypha', 'Sculptra', 'Stylage', 'Teosyal',
] as const;

export const ALL_CATEGORIES = [
  'All',
  'Dermal Fillers',
  'Lips',
  'Skinboosters',
  'Collagen Stimulators',
  'Polynucleotides',
  'Mesotherapy',
  'Korean Products',
  'Bestsellers',
] as const;

export const products: Product[] = [
  {
    id: 'aessoa-deep-lidocaine-1ml',
    name: 'Aessoa Deep Lidocaine 1ml',
    brand: 'Aessoa',
    manufacturer: 'Oreon Life Science',
    categories: ['Dermal Fillers', 'Korean Products'],
    countryOfOrigin: 'South Korea',
    description: 'Aessoa Deep Lidocaine is a unique dermal filler used to correct moderate to deep wrinkles. It is ideal for smoothing nasolabial folds, glabella lines, and marionette lines. Aessoa Deep contains a high concentration of hyaluronic acid with a thick, viscous gel providing long-lasting, natural results. It can also be used for lip augmentation.',
    packContents: ['1 x 1ml prefilled syringe', '27G needle recommended (not included)'],
    ingredients: ['Hyaluronic acid: 24 mg/ml', 'Lidocaine: 3 mg/ml'],
    benefits: ['Deep wrinkle correction', 'Volume restoration', 'Lip enhancement', 'Long-lasting results'],
    treatmentAreas: ['Nasolabial folds', 'Marionette lines', 'Glabella lines', 'Lip augmentation'],
    image: '/products/aessoa-deep-lidocaine-1ml.jpg',
    price: '€30',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'aessoa-ultra-lidocaine-1ml',
    name: 'Aessoa Ultra Lidocaine 1ml',
    brand: 'Aessoa',
    manufacturer: 'Oreon Life Science',
    categories: ['Dermal Fillers', 'Korean Products'],
    countryOfOrigin: 'South Korea',
    description: 'Aessoa Ultra Lidocaine is a dermal filler used to add volume and provide high lifting effects in the facial area. Due to its high cohesiveness and hardness, it acts like an implant in the mid to deep dermis. Recommended for facial contouring in cheeks, chin, jawline, forehead, and nose with results lasting up to 12 months.',
    packContents: ['1 x 1ml prefilled syringe', '25G needle recommended (not included)'],
    ingredients: ['Hyaluronic acid: 24 mg/ml', 'Lidocaine: 3 mg/ml'],
    benefits: ['Adds volume', 'High lifting effects', 'High cohesiveness and hardness', 'Acts like an implant'],
    treatmentAreas: ['Nasolabial folds', 'Forehead', 'Cheeks', 'Chin', 'Jawline', 'Nose'],
    image: '/products/aessoa-ultra-lidocaine-1ml.jpg',
    price: '€30',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'aliaxin-ev-essential-volume-1ml',
    name: 'Aliaxin EV Essential Volume 1ml',
    brand: 'Aliaxin',
    manufacturer: 'IBSA Farmaceutici',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'Switzerland',
    description: 'Aliaxin EV "Essential Volume" is a dermal filler specifically designed to restore lost facial volume and shape facial contours. This pure hyaluronic acid formula has optimal lifting capacity making it ideal for subcutaneous implants. It also rehydrates the skin and stimulates the tissue.',
    packContents: ['2 x 1ml prefilled syringes', '4 x 27G x 13mm TSK needles', '4 x 27G x 19mm TSK needles'],
    ingredients: ['25 mg/ml cross-linked hyaluronic acid', 'Cross-linking degree: 5/5'],
    benefits: ['Restore facial volume', 'Shape facial contours', 'Rehydration of the skin', 'Tissue stimulation'],
    treatmentAreas: ['Cheeks', 'Chin', 'Cheekbones'],
    image: '/products/aliaxin-ev-essential-volume-1ml.jpg',
    price: '€100',
    lidocaine: false,
    volume: '1ml',
  },
  {
    id: 'aliaxin-fl-1ml',
    name: 'Aliaxin FL Fine Lines 1ml',
    brand: 'Aliaxin',
    manufacturer: 'IBSA Farmaceutici',
    categories: ['Dermal Fillers', 'Lips'],
    countryOfOrigin: 'Switzerland',
    description: 'Aliaxin FL "Fine Lines" is a dermal hyaluronic acid filler specifically intended for lip treatments and treatments of fine lines. It has ideal viscosity for restoring skin firmness and natural definition, and is ideal to define the vermillion border of the lips. The gel structure guarantees high resistance to mechanical stress.',
    packContents: ['2 x 1ml prefilled syringes', '4 x 30G x 13mm TSK needles'],
    ingredients: ['25 mg/ml cross-linked hyaluronic acid', 'Cross-linking degree: 3/5'],
    benefits: ['Define the lips', 'Treat fine lines', 'Restore skin firmness and natural definition', 'Excellent diffusion in the skin'],
    treatmentAreas: ['Eye area', 'Lips', 'Nasolabial folds', 'Forehead'],
    image: '/products/aliaxin-fl-1ml.jpg',
    price: '€100',
    lidocaine: false,
    volume: '1ml',
  },
  {
    id: 'aliaxin-lv-lips-volume-1ml',
    name: 'Aliaxin LV Lips Volume 1ml',
    brand: 'Aliaxin',
    manufacturer: 'IBSA Farmaceutici',
    categories: ['Dermal Fillers', 'Lips'],
    countryOfOrigin: 'Switzerland',
    description: 'Aliaxin LV "Lips Volume" is a non-invasive HA dermal filler designed to give the lips a harmonious and natural look. The ultrapure hyaluronic acid integrates seamlessly into the skin. High viscosity provides a structure that guarantees high resistance to mechanical stress and excellent diffusion, restoring firmness and enhancing lip contour.',
    packContents: ['2 x 1ml prefilled syringes', '4 x 27G x 13mm TSK needles', '4 x 27G x 19mm TSK needles'],
    ingredients: ['25 mg/ml cross-linked hyaluronic acid', 'Cross-linking degree: 4/5'],
    benefits: ['Natural definition of the lips', 'Restores firmness in the skin', 'Ideal to add volume in the lips'],
    treatmentAreas: ['Lips', 'Perioral area'],
    image: '/products/aliaxin-lv-lips-volume-1ml.jpg',
    lidocaine: false,
    volume: '1ml',
  },
  {
    id: 'aliaxin-sr-shape-and-restore-1ml',
    name: 'Aliaxin SR Shape & Restore 1ml',
    brand: 'Aliaxin',
    manufacturer: 'IBSA Farmaceutici',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'Switzerland',
    description: 'Aliaxin SR "Shape & Restore" is a dermal filler ideal for dermal remodelling. Use Aliaxin SR for facial reshaping and replenishing facial fullness with natural and well-defined contours.',
    packContents: ['2 x 1ml prefilled syringes', '4 x 30G x 13mm TSK needles', '4 x 27G x 19mm TSK needles'],
    ingredients: ['22.5 mg/ml cross-linked hyaluronic acid', '2.5 mg/ml natural hyaluronic acid', 'Cross-linking degree: 2/5'],
    benefits: ['Facial remodelling', 'Replenish facial fullness', 'Natural and well-defined facial contours'],
    treatmentAreas: ['Cheeks', 'Chin', 'Nasolabial folds', 'Temples for sagging skin'],
    image: '/products/aliaxin-sr-shape-and-restore-1ml.jpg',
    lidocaine: false,
    volume: '1ml',
  },
  {
    id: 'aquashine-soft-filler-2ml',
    name: 'Aquashine Soft Filler 2ml',
    brand: 'Aquashine',
    manufacturer: 'Caregen',
    categories: ['Skinboosters', 'Mesotherapy', 'Korean Products'],
    countryOfOrigin: 'South Korea',
    description: 'Aquashine Soft Filler is an anti-wrinkle and skin rejuvenating filler composed of bioactive ingredients including hyaluronic acid, multi-vitamins, and amino acids. It reduces wrinkles, improves skin elasticity by generating new skin cells, and revitalizes tired skin by maximizing cell proliferation. Injected into the epidermal/superficial to mid dermis.',
    packContents: ['2 x 2ml syringes'],
    ingredients: ['Hyaluronic acid', 'Multi-vitamins', 'Amino acids'],
    benefits: ['Correct fine lines and wrinkles', 'Improve skin elasticity', 'Generate new skin cells', 'Revitalize the skin', 'Moisturise skin and tighten pores'],
    treatmentAreas: ['Face', 'Neck', 'Décolleté area'],
    image: '/products/aquashine-soft-filler-2ml.jpg',
    lidocaine: false,
    volume: '2ml',
  },
  {
    id: 'belotero-balance-lidocaine-1ml',
    name: 'Belotero Balance Lidocaine 1ml',
    brand: 'Belotero',
    manufacturer: 'Merz',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'Switzerland',
    description: 'Belotero Balance Lidocaine integrates seamlessly into the skin, allowing for immediate and smooth correction of medium to deep lines in the superficial and mid dermis. The cohesivity enables optimal skin integration and provides a volumizing effect. Contains lidocaine for a more comfortable injection.',
    packContents: ['1 x 1ml syringe', '1 x 27G needle', '1 x 30G needle'],
    ingredients: ['22.5 mg/ml cross-linked sodium hyaluronate', '3 mg/ml lidocaine'],
    benefits: ['Optimal skin integration', 'Correct medium to deep facial lines', 'Volumizing effect'],
    treatmentAreas: ['Glabellar lines', 'Nasolabial folds', 'Marionette lines', 'Lip contours', 'Lip volume', 'Oral commissures'],
    image: '/products/belotero-balance-lidocaine-1ml.jpg',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'belotero-intense-lidocaine-1ml',
    name: 'Belotero Intense Lidocaine 1ml',
    brand: 'Belotero',
    manufacturer: 'Merz',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'Switzerland',
    description: 'Belotero Intense Lidocaine provides optimal filling capacity and is the ideal filler for correcting fine to deep lines. Excellent tissue integration minimizes skin irregularities and provides natural-looking results. It can create a volumizing effect on nasolabial folds, marionette lines, lip contours, and lip volume.',
    packContents: ['1 x 1ml syringe', '2 x 27G needles'],
    ingredients: ['25.5 mg/ml cross-linked sodium hyaluronate', '3 mg/ml lidocaine'],
    benefits: ['Correct fine to deep lines', 'Excellent tissue integration', 'Create volume', 'Optimal filling capacity'],
    treatmentAreas: ['Nasolabial folds', 'Marionette lines', 'Lip contours', 'Lip volume', 'Oral commissures', "Cupid's bow"],
    image: '/products/belotero-intense-lidocaine-1ml.jpg',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'belotero-lips-contour-lidocaine-0-6ml',
    name: 'Belotero Lips Contour Lidocaine 0.6ml',
    brand: 'Belotero',
    manufacturer: 'Merz',
    categories: ['Dermal Fillers', 'Lips'],
    countryOfOrigin: 'Switzerland',
    description: 'Belotero Lips Contour Lidocaine is a cross-linked hyaluronic acid dermal filler designed for lip contouring and providing fullness to the lips. Ideal to restore the outline of the lips for a more youthful appearance. Part of a duo for subtle and natural lip enhancements alongside Belotero Lips Shape.',
    packContents: ['1 x 0.6ml syringe', '1 x 27G ½" needle', '1 x 30G ½" needle'],
    ingredients: ['22.5 mg/ml hyaluronic acid', '0.3% lidocaine'],
    benefits: ['Balance the lip shape', 'Enhanced curves and contours', 'Natural long-lasting results'],
    treatmentAreas: ['Lips', 'Lip outline'],
    image: '/products/belotero-lips-contour-lidocaine-0-6ml.jpg',
    lidocaine: true,
    volume: '0.6ml',
  },
  {
    id: 'belotero-lips-shape-lidocaine-0-6ml',
    name: 'Belotero Lips Shape Lidocaine 0.6ml',
    brand: 'Belotero',
    manufacturer: 'Merz',
    categories: ['Dermal Fillers', 'Lips'],
    countryOfOrigin: 'Switzerland',
    description: 'Belotero Lips Shape with Lidocaine is an injectable hyaluronic filler ideal for lip augmentation and enhancing the volume of the upper and lower lip. It improves the appearance of the lips by adding shape, structure, and volume. Part of a duo with Belotero Lips Contour for subtle and natural lip enhancements.',
    packContents: ['1 x 0.6ml syringe', '2 x 27G ½" needles'],
    ingredients: ['25.5 mg/ml hyaluronic acid', '0.3% lidocaine'],
    benefits: ['Increased lip volume', 'Enhanced curves and contours', 'Natural long-lasting results'],
    treatmentAreas: ['Upper lip', 'Lower lip'],
    image: '/products/belotero-lips-shape-lidocaine-0-6ml.jpg',
    lidocaine: true,
    volume: '0.6ml',
  },
  {
    id: 'e-p-t-q-s300-lidocaine-1-1ml',
    name: 'E.p.t.q. S300 Lidocaine 1.1ml',
    brand: 'E.p.t.q',
    manufacturer: 'Jetema',
    categories: ['Dermal Fillers', 'Korean Products'],
    countryOfOrigin: 'South Korea',
    description: 'E.p.t.q S300 with Lidocaine is perfect for treating middle-range to deep wrinkles in the forehead and correcting deep skin irregularities such as nasolabial folds, perioral wrinkles, and puppet lines. Ideal for creating volume in cheeks and ear areas. Medium consistency makes it easy to redefine nose, cheeks, and chin.',
    packContents: ['1 x 1.1ml syringe', '2 x 27G ½" needles', 'Instruction leaflet'],
    ingredients: ['24 mg/ml cross-linked hyaluronic acid', 'Lidocaine 0.3%'],
    benefits: ['Treat middle to deep wrinkles', 'Volume creation in cheeks', 'Easy redefining of nose and chin'],
    treatmentAreas: ['Nasolabial folds', 'Perioral wrinkles', 'Cheeks', 'Lips', 'Nose', 'Chin', 'Ear'],
    image: '/products/e-p-t-q-s300-lidocaine-1-1ml.jpg',
    lidocaine: true,
    volume: '1.1ml',
  },
  {
    id: 'fillmed-art-filler-fine-lines-1ml',
    name: 'Fillmed Art Filler Fine Lines 1ml',
    brand: 'Fillmed',
    manufacturer: 'Fillmed Laboratories',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'France',
    description: 'Fillmed Art Filler Fine Lines with Lidocaine is a hyaluronic acid gel filler designed to treat fine lines, superficial wrinkles, and tiny skin folds. The soft, smooth texture makes it easy to spread evenly and fill in fine lines. Part of the exclusive Art Filler collection designed for superficial-to-deep wrinkle correction.',
    packContents: ['2 x 1ml syringes', '4 x 30G needles'],
    ingredients: ['20 mg/ml hyaluronic acid', '3 mg/ml lidocaine'],
    benefits: ['Fill fine lines, tiny skin folds, and superficial wrinkles', 'Easy to shape texture', 'Contains lidocaine for comfort'],
    treatmentAreas: ['Lips', "Crow's feet", 'Lines around the mouth', 'Superficial wrinkles'],
    image: '/products/fillmed-art-filler-fine-lines-1ml.jpg',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'fillmed-art-filler-lips-soft-1ml',
    name: 'Fillmed Art Filler Lips Soft 1ml',
    brand: 'Fillmed',
    manufacturer: 'Fillmed Laboratories',
    categories: ['Dermal Fillers', 'Lips'],
    countryOfOrigin: 'France',
    description: 'Art Filler Lips Soft by Fillmed is a dermal filler designed specifically for lip enhancement using advanced Tri-Hyal Technology. It combines three types of hyaluronic acids for a perfect balance of elasticity, cohesiveness, and volume, delivering smooth, natural-looking results. Enhances lip volume, shape, and contour while hydrating fine lines around the mouth.',
    packContents: ['1 x 1ml syringe', '2 x 30G ½" needles'],
    ingredients: ['25 mg/ml hyaluronic acid', '3 mg/ml lidocaine'],
    benefits: ['Smooth, subtle augmentation for fuller, more defined lips', 'Hydrate the lips and add volume', 'Soft, flexible gel for easy injection and precise shaping', 'Fewer touch-ups needed'],
    treatmentAreas: ['Lips'],
    image: '/products/fillmed-art-filler-lips-soft-1ml.jpg',
    price: '€58',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'fillmed-art-filler-lips-1ml',
    name: 'Fillmed Art Filler Lips 1ml',
    brand: 'Fillmed',
    manufacturer: 'Fillmed Laboratories',
    categories: ['Dermal Fillers', 'Lips'],
    countryOfOrigin: 'France',
    description: 'Fillmed Art Filler Lips is a soft tissue HA filler designed to shape, volumize, and hydrate the lips. It can also smooth out superficial lines. The soft smooth texture makes it easy to spread evenly and sculpt into the correct shape. Contains Lidocaine to reduce pain and ensure comfort during treatment.',
    packContents: ['2 x 1ml syringes', '4 x 27G needles'],
    ingredients: ['25 mg/ml hyaluronic acid', '3 mg/ml lidocaine'],
    benefits: ['Shape, volumize and hydrate the lips', 'Smooth out fine lines', 'Plump and define lip size', 'Easy to shape texture'],
    treatmentAreas: ['Lips', 'Superficial lines'],
    image: '/products/fillmed-art-filler-lips-1ml.jpg',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'fillmed-nctf-135ha-3ml',
    name: 'Fillmed NCTF 135HA 3ml (5 vials)',
    brand: 'Fillmed',
    manufacturer: 'Fillmed Laboratories',
    categories: ['Skinboosters', 'Mesotherapy', 'Bestsellers'],
    countryOfOrigin: 'France',
    description: 'Fillmed NCTF 135HA is an anti-ageing mesotherapy product for intense revitalization, hydration of tired or loose skin, treatment of wrinkles, and optimizing skin brightness and radiance. The formula contains 55 active ingredients including vitamins, amino acids, proteins, free radicals and anti-oxidants to stimulate and repair aging skin.',
    packContents: ['5 x 3ml vials'],
    ingredients: ['5 mg/ml hyaluronic acid', '12 Vitamins (A, B, C & E)', '6 Minerals', '24 Amino acids', '5 Nucleic Acids', '6 Co-enzymes'],
    benefits: ['Intense revitalization', 'Skin hydration', 'Treat superficial wrinkles', 'Improve skin brightness and radiance'],
    treatmentAreas: ['Face', 'Neck', 'Décolleté', 'Back of the hands', 'Inside of the arms', 'Abdomen'],
    image: '/products/fillmed-nctf-135ha-3ml.jpg',
    lidocaine: false,
    volume: '3ml',
  },
  {
    id: 'harmonyca-lidocaine-1-25ml',
    name: 'HarmonyCa Lidocaine 1.25ml',
    brand: 'HarmonyCa',
    manufacturer: 'Allergan',
    categories: ['Collagen Stimulators', 'Bestsellers'],
    countryOfOrigin: 'Israel',
    description: 'HarmonyCa is comprised of Calcium Hydroxyapatite microspheres embedded within cross-linked hyaluronic acid. CaHA stimulates collagen production while HA forms a supporting extracellular matrix. The microsphere diameter (25–45 microns) minimizes migration risk and ensures smooth appearance with deep skin hydration. Injected in deep and sub-dermal layers.',
    packContents: ['2 x 1.25ml syringes'],
    ingredients: ['20 mg/ml hyaluronic acid', '55.7% Calcium Hydroxyapatite', 'Phosphate buffer', '0.3% lidocaine'],
    benefits: ['Provides strong volumizing, lifting effect', 'Promotes generation of natural collagen', 'Biocompatible and biodegradable'],
    treatmentAreas: ['Face'],
    image: '/products/harmonyca-lidocaine-1-25ml.jpg',
    lidocaine: true,
    volume: '1.25ml',
  },
  {
    id: 'hyacorp-face-1ml',
    name: 'HYAcorp Face 1ml',
    brand: 'HYAcorp',
    manufacturer: 'Bio Science',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'Germany',
    description: 'HYAcorp Face is an absorbable skin implant produced from non-animal origin hyaluronic acid. Indicated for restoration of facial volume and contour by replacing lost hyaluronic acid in the skin. For filling folds, medium to deep folds, nasolabial folds, cheek area, and glabella folds. Do not inject in the periorbital region.',
    packContents: ['1 x 1ml syringe', '2 x 30G needles'],
    ingredients: ['2 mg hyaluronic acid', '20 mg cross-linked hyaluronic acid'],
    benefits: ['Restore facial volume', 'Correct facial folds'],
    treatmentAreas: ['Nasolabial folds', 'Cheek area', 'Glabella folds'],
    image: '/products/hyacorp-face-1ml.jpg',
    price: '€54',
    lidocaine: false,
    volume: '1ml',
  },
  {
    id: 'hyacorp-lips-1ml',
    name: 'HYAcorp Lips 1ml',
    brand: 'HYAcorp',
    manufacturer: 'Bio Science',
    categories: ['Dermal Fillers', 'Lips'],
    countryOfOrigin: 'Germany',
    description: 'HYAcorp Lips is an absorbable skin implant with a high level of purity intended for the restoration of volume and contour of the lips. Produced from non-animal origin hyaluronic acid and intended for single use only.',
    packContents: ['1 x 1ml syringe', '2 x 30G needles'],
    ingredients: ['2 mg hyaluronic acid', '16 mg cross-linked hyaluronic acid'],
    benefits: ['Contour of the lips', 'Create lip volume'],
    treatmentAreas: ['Lips'],
    image: '/products/hyacorp-lips-1ml.jpg',
    price: '€52',
    lidocaine: false,
    volume: '1ml',
  },
  {
    id: 'inno-ce-mesha-scars-1-2ml',
    name: 'Inno-CE Mesha Scars 1.2ml',
    brand: 'Innoaesthetics',
    manufacturer: 'Laboratorio Innoaesthetics',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'Spain',
    description: 'Inno-CE Mesha Scars is a specialized dermal filler CE-certified and developed for the treatment of scars and skin depressions. Formulated for targeted correction in areas requiring precise volumization.',
    packContents: ['1 x 1.2ml syringe'],
    ingredients: ['Cross-linked hyaluronic acid'],
    benefits: ['Scar correction', 'Skin depression treatment', 'Targeted volumization'],
    treatmentAreas: ['Scars', 'Skin depressions'],
    image: '/products/inno-ce-mesha-scars-1-2ml.jpg',
    price: '€48',
    lidocaine: false,
    volume: '1.2ml',
  },
  {
    id: 'juvederm-ultra-smile-lidocaine-0-55ml',
    name: 'Juvéderm Ultra Smile Lidocaine 0.55ml',
    brand: 'Juvederm',
    manufacturer: 'Allergan',
    categories: ['Dermal Fillers', 'Lips'],
    countryOfOrigin: 'France',
    description: 'Juvéderm Ultra Smile Lidocaine is specifically formulated to provide full, soft, natural-looking lips and is used to smooth fine lines and enhance the mouth area. Designed to enhance lip volume, redefine lip shape, and correct vertical lip lines. Contains lidocaine to ensure a more comfortable injection.',
    packContents: ['2 x 0.55ml syringes', '2 x 30G ½" needles'],
    ingredients: ['24 mg/ml hyaluronic acid', '0.3% lidocaine'],
    benefits: ['Create lip volume', 'Enhance mouth area', 'Redefine lip shape', 'Correct fine lines around the mouth'],
    treatmentAreas: ['Lips'],
    image: '/products/juvederm-ultra-smile-lidocaine-0-55ml.jpg',
    price: '€105',
    lidocaine: true,
    volume: '0.55ml',
  },
  {
    id: 'juvederm-volbella-lidocaine-1ml',
    name: 'Juvéderm Volbella Lidocaine 1ml',
    brand: 'Juvederm',
    manufacturer: 'Allergan',
    categories: ['Dermal Fillers', 'Lips'],
    countryOfOrigin: 'France',
    description: 'Juvéderm Volbella Lidocaine is a facial filler specifically developed for the lips and mouth area. Designed for gently restoring lip volume and defining lip contours, the smooth gel provides a soft, natural result. Can also treat superficial facial lines and wrinkles. Contains lidocaine for more comfortable treatment.',
    packContents: ['2 x 1ml syringes', '4 x 30G ½" needles'],
    ingredients: ['15 mg/ml hyaluronic acid', '0.3% lidocaine', 'Phosphate buffer pH 7.2'],
    benefits: ['Restore lip volume', 'Redefine contours in the mouth area', 'Treat superficial facial lines and wrinkles'],
    treatmentAreas: ['Lips', 'Infraorbital area'],
    image: '/products/juvederm-volbella-lidocaine-1ml.jpg',
    price: '€195',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'juvederm-volift-retouch-lido-0-55ml',
    name: 'Juvéderm Volift Retouch Lidocaine 0.55ml',
    brand: 'Juvederm',
    manufacturer: 'Allergan',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'France',
    description: 'Juvéderm Volift Retouch is ideal for filling, smoothing, and rejuvenation of the midface. Use it to reduce nasolabial folds and restore natural contours. The 0.55ml size syringes are ideal for touch-up sessions in areas requiring a smaller amount of gel. Contains lidocaine for a more comfortable injection.',
    packContents: ['2 x 0.55ml syringes', '4 x 30G ½" needles'],
    ingredients: ['17 mg/ml hyaluronic acid', '0.3% lidocaine'],
    benefits: ['Reduce nasolabial folds', 'Restore natural face contours', 'Ideal for touch-up sessions'],
    treatmentAreas: ['Cheeks', 'Cheekbones', 'Smile lines', 'Jawlines'],
    image: '/products/juvederm-volift-retouch-lido-0-55ml.jpg',
    price: '€125',
    lidocaine: true,
    volume: '0.55ml',
  },
  {
    id: 'juvederm-voluma-lidocaine-1ml',
    name: 'Juvéderm Voluma Lidocaine 1ml',
    brand: 'Juvederm',
    manufacturer: 'Allergan',
    categories: ['Dermal Fillers', 'Bestsellers'],
    countryOfOrigin: 'France',
    description: 'Juvéderm Voluma Lidocaine is an innovative injectable facial filler that contains hyaluronic acid to restore and enhance volume in the cheeks and chin. Use it to enhance the overall shape of the face and to create a smooth and natural look. Contains lidocaine to ensure a more comfortable injection.',
    packContents: ['2 x 1ml syringes', '4 x 27G ½" needles'],
    ingredients: ['20 mg/ml hyaluronic acid', '0.3% lidocaine'],
    benefits: ['Restore lost skin volume', 'Enhance volume in cheeks and chin', 'Create a smooth and natural look', 'Enhance the overall shape of the face'],
    treatmentAreas: ['Cheeks', 'Chin'],
    image: '/products/juvederm-voluma-lidocaine-1ml.jpg',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'juvederm-volux-lidocaine-1ml',
    name: 'Juvéderm Volux Lidocaine 1ml',
    brand: 'Juvederm',
    manufacturer: 'Allergan',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'France',
    description: 'Juvéderm Volux Lidocaine is a resorbable non-permanent high-density filler from the Juvéderm VYCROSS line. Formulated to restore and create facial volume, treat glabellar lines and skin asymmetries. Results are natural and can last 18 to 24 months. Based on cross-linked hyaluronic acid of non-animal origin.',
    packContents: ['2 x 1ml syringes', '4 x 27G ½" needles'],
    ingredients: ['25 mg/ml hyaluronic acid', '0.3% lidocaine'],
    benefits: ['Restores and creates facial volume', 'Smooths glabellar lines and wrinkles', 'Enhances overall shape of the face', 'Natural long-lasting results (18–24 months)'],
    treatmentAreas: ['Chin', 'Jaw'],
    image: '/products/juvederm-volux-lidocaine-1ml.jpg',
    price: '€195',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'kairax-deep-1ml',
    name: 'Kairax Deep 1ml',
    brand: 'Kairax',
    manufacturer: 'Victoria Sun Inc.',
    categories: ['Dermal Fillers', 'Korean Products'],
    countryOfOrigin: 'South Korea',
    description: 'Kairax Deep is a high-quality hyaluronic acid filler combining traditional and mechanical cross-linking techniques for superior viscoelasticity. Fully CE approved and containing lidocaine, it is designed for deep wrinkle correction and volume enhancement in areas such as the lips, glabella lines, nasolabial folds, and nose contouring.',
    packContents: ['1 x 1ml syringe', '2 x 27G x ½" needles'],
    ingredients: ['24 mg/ml cross-linked hyaluronic acid', '0.3% lidocaine'],
    benefits: ['Restores skin for a youthful appearance', 'Enhances natural, healthy skin glow', 'Provides intense hydration', 'Smooths deep wrinkles and folds', 'Restores lost volume and improves facial contours'],
    treatmentAreas: ['Lips', 'Glabella lines', 'Nasolabial folds', 'Marionette lines', 'Nose', 'Forehead contouring'],
    image: '/products/kairax-deep-1ml.jpg',
    price: '€29',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'kairax-supq-1ml',
    name: 'Kairax Sub-Q 1ml',
    brand: 'Kairax',
    manufacturer: 'Victoria Sun Inc.',
    categories: ['Dermal Fillers', 'Korean Products'],
    countryOfOrigin: 'South Korea',
    description: 'Kairax Sub-Q is a high-viscoelasticity hyaluronic acid filler using advanced Korean technology for enhanced volume and contouring. Fully CE approved and containing lidocaine, ideal for volumizing cheeks, jawline, and nasolabial folds. Provides excellent moisture retention while ensuring minimal swelling and bruising.',
    packContents: ['1 x 1ml syringe', '2 x 25G x ½" needles'],
    ingredients: ['24 mg/ml cross-linked hyaluronic acid', '0.3% lidocaine'],
    benefits: ['Restores skin for a youthful appearance', 'Enhances natural skin glow', 'Provides deep hydration', 'Smooths deep wrinkles and folds', 'Restores lost volume and improves contours'],
    treatmentAreas: ['Cheeks', 'Jawline', 'Nasolabial folds', 'Body contouring'],
    image: '/products/kairax-supq-1ml.jpg',
    price: '€35',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'lumifil-kiss-1ml',
    name: 'Lumifil Kiss 1ml',
    brand: 'Lumifil',
    manufacturer: 'BNC Korea',
    categories: ['Dermal Fillers', 'Lips', 'Korean Products'],
    countryOfOrigin: 'South Korea',
    description: 'Lumifil Kiss Lidocaine is a high-quality hyaluronic acid dermal filler tailored for lip enhancement. It adds natural-looking volume, definition, and hydration while preserving the lips\' softness and flexibility. With a smooth gel texture and ideal viscoelasticity, it allows for precise application creating beautifully contoured lips.',
    packContents: ['1 x 1ml syringe'],
    ingredients: ['20 mg/ml cross-linked hyaluronic acid', '0.3% lidocaine'],
    benefits: ['Enhance lip volume and shape', 'High viscoelasticity for lasting volume', 'Provides natural definition and symmetry', 'Delivers intense hydration', 'Smooth texture for seamless application'],
    treatmentAreas: ['Lip augmentation and enhancement', 'Lip contouring and definition', 'Correcting lip asymmetry', 'Restoring lip volume'],
    image: '/products/lumifil-kiss-1ml.jpg',
    price: '€29',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'mesoestetic-mesofiller-global-1ml',
    name: 'Mesoestetic Mesofiller Global 1ml',
    brand: 'Mesoestetic',
    manufacturer: 'Laboratorio Innoaesthetics',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'Spain',
    description: 'Mesoestetic Mesofiller Global is a versatile CE-certified dermal filler for global facial correction and rejuvenation. Designed for volume restoration and wrinkle correction, offering natural-looking results with volume discounts available for bulk purchases.',
    packContents: ['1 x 1ml syringe'],
    ingredients: ['Cross-linked hyaluronic acid'],
    benefits: ['Global facial correction', 'Volume restoration', 'Wrinkle correction', 'Natural-looking results'],
    treatmentAreas: ['Face'],
    image: '/products/mesoestetic-mesofiller-global-1ml.jpg',
    price: '€70',
    lidocaine: false,
    volume: '1ml',
  },
  {
    id: 'neauvia-intense-flux-1ml',
    name: 'Neauvia Intense Flux 1ml',
    brand: 'Neauvia',
    manufacturer: 'Matexlab',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'Italy',
    description: 'Neauvia Intense Flux is an organic filler with low viscoelasticity and high biointegration, intended for deep tissue restoration of volume in moderate to strongly aged skin. Suitable for injection into the intradermal layer. The balanced crosslinking degree makes it highly adaptive to tissue, helping to volumize the anatomic area.',
    packContents: ['1 x 1ml syringe'],
    ingredients: ['26 mg/ml HA, PEG polymer cross-linked', 'Glycine and L-Proline'],
    benefits: ['High HA concentration and low viscoelasticity', 'Deep tissue restoration of volume', 'Balanced crosslinking, highly adaptive to tissue'],
    treatmentAreas: ['Nasolabial folds', 'Lips augmentation', 'Face contours lifting', 'Chin modeling', 'Cheek modeling'],
    image: '/products/neauvia-intense-flux-1ml.jpg',
    price: '€52',
    lidocaine: false,
    volume: '1ml',
  },
  {
    id: 'neauvia-intense-lips-1ml',
    name: 'Neauvia Intense Lips 1ml',
    brand: 'Neauvia',
    manufacturer: 'Matexlab',
    categories: ['Dermal Fillers', 'Lips'],
    countryOfOrigin: 'Italy',
    description: 'Neauvia Intense Lips contains 24 mg/ml of HA to provide optimal results in the delicate lip area. Use for augmentation, contouring, and revitalization of lips. The product contains amino acids Glycine and L-Proline, which are main ingredients in collagen, ensuring elasticity of the lips and providing a natural touch.',
    packContents: ['1 x 1ml syringe'],
    ingredients: ['24 mg/ml HA, cross-linked with PEG', 'Glycine and L-Proline'],
    benefits: ['High HA concentration for great hydration', 'Augmentation and modelling of lips'],
    treatmentAreas: ['Lips'],
    image: '/products/neauvia-intense-lips-1ml.jpg',
    price: '€52',
    lidocaine: false,
    volume: '1ml',
  },
  {
    id: 'neuramis-deep-lidocaine-1ml',
    name: 'Neuramis Deep Lidocaine 1ml',
    brand: 'Neuramis',
    manufacturer: 'Medytox',
    categories: ['Dermal Fillers', 'Korean Products'],
    countryOfOrigin: 'South Korea',
    description: 'Neuramis Deep Lidocaine is a high-quality dermal filler based on cross-linked hyaluronic acid featuring advanced SHAPET technology, which minimizes side effects and ensures consistent particle size and high purity. Particularly effective for correcting wrinkles and folds in the lower face with long-lasting, natural-looking results.',
    packContents: ['1 x 1ml prefilled syringe', '2 x 27G ½" disposable needles'],
    ingredients: ['Hyaluronic acid 20 mg/ml', 'Lidocaine 3 mg/ml', 'Phosphate buffered saline, pH 7.0'],
    benefits: ['Long-lasting and natural-looking results', 'Innovative SHAPET Technology', 'Enhance facial contours and restore volume', 'Smooths moderate to deep wrinkles'],
    treatmentAreas: ['Nasolabial folds', 'Marionette lines', 'Frown lines', 'Lips', 'Cheek', 'Chin', 'Nose bridge'],
    image: '/products/neuramis-deep-lidocaine-1ml.jpg',
    price: '€34',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'nucleofill-strong-1-5ml',
    name: 'Nucleofill Strong 1.5ml',
    brand: 'Nucleofill',
    manufacturer: 'Promoitalia',
    categories: ['Polynucleotides', 'Bestsellers'],
    countryOfOrigin: 'Italy',
    description: 'Nucleofill Strong 1.5ml is an advanced skin biostimulation treatment designed to deeply rejuvenate and strengthen the skin. Its polynucleotide-based formula (2.5%) stimulates collagen and elastin production, enhances hydration, and improves skin structure. With powerful antioxidant and lifting effects, it reduces signs of aging without adding volume.',
    packContents: ['1 x 1.5ml syringe', '2 x 30G ½" 13mm needles'],
    ingredients: ['37.5 mg/ml polynucleotides (25 mg/ml)'],
    benefits: ['Deep skin rejuvenation', 'Enhances skin structure', 'Provides lifting and firming effects', 'Intense hydration', 'Powerful antioxidant protection'],
    treatmentAreas: ['Face', 'Neck', 'Décolleté', 'Hands', 'Abdomen', 'Buttocks', 'Thighs'],
    image: '/products/nucleofill-strong-1-5ml.jpg',
    lidocaine: false,
    volume: '1.5ml',
  },
  {
    id: 'profhilo-h-l-2ml',
    name: 'Profhilo H+L 2ml',
    brand: 'Profhilo',
    manufacturer: 'IBSA Farmaceutici',
    categories: ['Skinboosters', 'Bestsellers'],
    countryOfOrigin: 'Italy',
    description: 'Profhilo H+L is a stabilized hyaluronic acid (HA) based product for skin remodeling and treating skin laxity — not just for filling lines and wrinkles. Used in areas affected by skin laxity such as the malar and submalar areas. Nourishes dermal cells, restores skin firmness, and improves tissue quality significantly.',
    packContents: ['1 x 2ml prefilled syringe', '2 x 29G ½" needles'],
    ingredients: ['Hyaluronic acid: 3.2% — 32 mg (H-HA)/2ml + 32 mg (L-HA)/2ml', 'Sodium chloride buffered saline solution'],
    benefits: ['Improvement in tissue quality', 'Skin remodelling', 'Treatment of skin laxity', 'Restore skin firmness'],
    treatmentAreas: ['Face', 'Neck'],
    image: '/products/profhilo-h-l-2ml.jpg',
    lidocaine: false,
    volume: '2ml',
  },
  {
    id: 'restylane-defyne-lidocaine-1ml',
    name: 'Restylane Defyne Lidocaine 1ml',
    brand: 'Restylane',
    manufacturer: 'Galderma',
    categories: ['Dermal Fillers', 'Bestsellers'],
    countryOfOrigin: 'Sweden',
    description: 'Restylane Defyne Lidocaine is a soft-gel filler designed to give a lifted, youthful appearance. A solution for deep facial wrinkles and folds or to replace lost skin volume. Ideal for treating deep nasolabial folds. Optimal Balance Technology (OPT) allows the filler to integrate smoothly into the skin. Contains lidocaine for comfort.',
    packContents: ['1 x 1ml syringe', '2 x 27G ½" needles'],
    ingredients: ['20 mg/ml cross-linked hyaluronic acid', '3 mg/ml lidocaine'],
    benefits: ['Treats deep wrinkles and lines', 'Reduces nasolabial folds and marionette lines'],
    treatmentAreas: ['Nasolabial folds', 'Marionette lines'],
    image: '/products/restylane-defyne-lidocaine-1ml.jpg',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'restylane-lidocaine-1ml',
    name: 'Restylane Lidocaine 1ml',
    brand: 'Restylane',
    manufacturer: 'Galderma',
    categories: ['Dermal Fillers', 'Bestsellers'],
    countryOfOrigin: 'Sweden',
    description: 'Restylane Lidocaine is used to add volume and fullness to the skin and to correct fine lines and wrinkles between the eyebrows, on the forehead, and the bilateral lines between the nose and mouth (nasolabial folds). Can also be used for lip enhancement. Contains lidocaine for a more comfortable injection.',
    packContents: ['1 x 1ml syringe', '2 x needles'],
    ingredients: ['20 mg/ml hyaluronic acid', '3 mg/ml lidocaine'],
    benefits: ['Treatment of fine lines, wrinkles and folds', 'Lip enhancement'],
    treatmentAreas: ['Eyebrows', 'Forehead', 'Nose', 'Mouth', 'Lips'],
    image: '/products/restylane-lidocaine-1ml.jpg',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'restylane-lyft-lidocaine-1ml',
    name: 'Restylane Lyft Lidocaine 1ml',
    brand: 'Restylane',
    manufacturer: 'Galderma',
    categories: ['Dermal Fillers', 'Bestsellers'],
    countryOfOrigin: 'Sweden',
    description: 'Restylane Lyft Lidocaine is a hyaluronic acid-based filler suitable for injection into the deep dermis to superficial subcutis. Use it to correct moderate to severe facial folds and wrinkles such as nose-to-mouth lines, frown lines, chin, and cheeks. Contains lidocaine for a more comfortable injection.',
    packContents: ['1 x 1ml syringe', '2 x needles'],
    ingredients: ['20 mg/ml hyaluronic acid', '3 mg/ml lidocaine'],
    benefits: ['Correction of moderate to severe facial folds and wrinkles', 'Cheek augmentation'],
    treatmentAreas: ['Nose-to-mouth lines', 'Frown lines', 'Chin', 'Cheeks'],
    image: '/products/restylane-lyft-lidocaine-1ml.jpg',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'revanesse-contour-lidocaine-1-2ml',
    name: 'Revanesse Contour+ Lidocaine 1.2ml',
    brand: 'Revanesse',
    manufacturer: 'Prollenium Medical',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'Canada',
    description: 'Revanesse Contour+ is the newest member of the Revanesse family — a highly cross-linked hyaluronic acid gel ideal for facial contouring and shaping. Restores and adds volume using HA gel perfect for large volume treatments such as chin and jaw augmentation and nose bridge correction.',
    packContents: ['2 x 1.2ml syringes'],
    ingredients: ['25 mg/ml hyaluronic acid', '3 mg/ml lidocaine'],
    benefits: ['Volumize skin', 'Replace lost hyaluronic acid', 'Ideal for large volume treatments'],
    treatmentAreas: ['Chin augmentation', 'Jaw augmentation', 'Nose bridge correction'],
    image: '/products/revanesse-contour-lidocaine-1-2ml.jpg',
    price: '€150',
    lidocaine: true,
    volume: '1.2ml',
  },
  {
    id: 'revofil-fine-1ml',
    name: 'Revofil Fine 1ml',
    brand: 'Revofil',
    manufacturer: 'Caregen',
    categories: ['Dermal Fillers', 'Korean Products'],
    countryOfOrigin: 'South Korea',
    description: 'Revofil Fine is a soft, non-invasive dermal filler designed to treat all moderate wrinkles on the face and hands including soft lines, superficial lines, and caved scars. A special formula with biometric peptides and cross-linked hyaluronic acid gives more natural and long-lasting results. Pack consists of 2 syringes.',
    packContents: ['2 x 1ml syringes', '1 x 30G ½" needle'],
    ingredients: ['23 mg/ml hyaluronic acid', 'Oligopeptide-72', 'Oligopeptide-50'],
    benefits: ['Treat soft lines, superficial lines, and caved scars'],
    treatmentAreas: ['Face rejuvenation', 'Hand rejuvenation'],
    image: '/products/revofil-fine-1ml.jpg',
    price: '€77',
    lidocaine: false,
    volume: '1ml',
  },
  {
    id: 'revolax-deep-lidocaine-1-1ml',
    name: 'Revolax Deep Lidocaine 1.1ml',
    brand: 'Revolax',
    manufacturer: 'Across',
    categories: ['Dermal Fillers', 'Korean Products', 'Bestsellers'],
    countryOfOrigin: 'South Korea',
    description: 'Revolax Deep Lidocaine is a thick and longer-lasting gel used to treat deep wrinkles and nasolabial folds, or for augmentation of the cheeks, chin, and lips. This mono-phasic HA filler is injected in deep dermis or subcutaneous tissue. Biodegradable, non-animal-based, crystal-clear cross-linked filler with high viscoelasticity.',
    packContents: ['1 x 1.1ml syringe', '2 x 27G needles'],
    ingredients: ['24 mg/ml cross-linked hyaluronic acid', '0.3% lidocaine'],
    benefits: ['Thick and longer-lasting gel', 'Deep wrinkle correction', 'Excellent volume and lift'],
    treatmentAreas: ['Deep wrinkles and nasolabial folds', 'Cheeks', 'Chin', 'Lips'],
    image: '/products/revolax-deep-lidocaine-1-1ml.jpg',
    lidocaine: true,
    volume: '1.1ml',
  },
  {
    id: 'revolax-sub-q-lidocaine-1-1ml',
    name: 'Revolax Sub-Q Lidocaine 1.1ml',
    brand: 'Revolax',
    manufacturer: 'Across',
    categories: ['Dermal Fillers', 'Korean Products', 'Bestsellers'],
    countryOfOrigin: 'South Korea',
    description: 'Revolax Sub-Q Lidocaine has the thickest properties within the product line. With its advanced ability to mold, maintain structure, and longevity, it is recommended for treatment of deep to extremely severe wrinkles including nasolabial and face contours. Biodegradable, non-animal-based, cross-linked filler for subcutaneous implantation.',
    packContents: ['1 x 1.1ml syringe', '2 x 25G needles'],
    ingredients: ['24 mg/ml cross-linked hyaluronic acid', '0.3% lidocaine'],
    benefits: ['Thickest formula in the Revolax range', 'Treatment of deep to extremely severe wrinkles', 'Advanced molding and structure maintenance'],
    treatmentAreas: ['Nasolabial folds', 'Face', 'Cheek', 'Chin', 'Nose'],
    image: '/products/revolax-sub-q-lidocaine-1-1ml.jpg',
    lidocaine: true,
    volume: '1.1ml',
  },
  {
    id: 'saypha-filler-1ml',
    name: 'Saypha Filler 1ml',
    brand: 'Saypha',
    manufacturer: 'Croma-Pharma',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'Austria',
    description: 'Saypha Filler is the replacement for the previous Princess Filler. It is a universal product appropriate for different aesthetic treatments such as correcting moderate facial wrinkles and lines, as well as enhancing lip volume. Suitable for all areas of the face, specifically perioral wrinkles, lip contour, and increasing lip volume.',
    packContents: ['1 x 1ml syringe'],
    ingredients: ['Cross-linked hyaluronic acid'],
    benefits: ['Can be used in all areas of the face', 'Volumize lips', 'Correct moderate lines and wrinkles'],
    treatmentAreas: ['Lips', 'Face'],
    image: '/products/saypha-filler-1ml.jpg',
    price: '€42',
    lidocaine: false,
    volume: '1ml',
  },
  {
    id: 'saypha-lips-lidocaine-1ml',
    name: 'Saypha Lips Lidocaine 1ml',
    brand: 'Saypha',
    manufacturer: 'Croma-Pharma',
    categories: ['Dermal Fillers', 'Lips'],
    countryOfOrigin: 'Austria',
    description: 'Saypha Lips Lidocaine 1ml is a premium dermal filler specifically designed for lip augmentation and perioral wrinkle correction. Formulated with highly purified hyaluronic acid for natural, smooth, and long-lasting results. Enhanced with lidocaine for a more comfortable experience. Ideal for enhancing lip volume, defining contour, and smoothing fine lines around the mouth.',
    packContents: ['1 x 1ml syringe'],
    ingredients: ['Cross-linked hyaluronic acid: 23 mg/ml', 'Lidocaine: 0.3%'],
    benefits: ['Restore fullness and shape of the lips', 'Smooth fine lines and perioral wrinkles', 'Ideal for accurate lip shaping and subtle definition', 'Safe and biocompatible'],
    treatmentAreas: ['Lips', 'Vermilion border', "Cupid's bow", 'Perioral lines'],
    image: '/products/saypha-lips-lidocaine-1ml.jpg',
    price: '€50',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'sculptra-5ml',
    name: 'Sculptra 2 × 5ml',
    brand: 'Sculptra',
    manufacturer: 'Galderma',
    categories: ['Collagen Stimulators', 'Bestsellers'],
    countryOfOrigin: 'Sweden',
    description: 'Sculptra is a next-generation collagen biostimulator made from poly-L-lactic acid (PLLA) that works deep in the dermis to restore facial volume, improve skin structure, and reduce visible signs of aging. By primarily stimulating type I collagen production, it targets the root cause of facial aging. Results develop over time and can last up to two years.',
    packContents: ['2 x 5ml vials (sterile powder, reconstituted with sterile water)'],
    ingredients: ['150 mg Poly-L-lactic acid', '90 mg Sodium carboxymethylcellulose', '127.5 mg Non-pyrogenic mannitol'],
    benefits: ['Restores lost facial collagen and volume', 'Reduces facial lines, wrinkles, and folds', 'Can lift sagging skin or slim contours', 'Targets the root cause of aging', 'Long-lasting results for up to 2 years'],
    treatmentAreas: ['Cheeks', 'Submalar area', 'Temples'],
    image: '/products/sculptra-5ml.jpg',
    lidocaine: false,
    volume: '5ml',
  },
  {
    id: 'stylage-bi-soft-m-lidocaine',
    name: 'Stylage Bi-Soft M Lidocaine 1ml',
    brand: 'Stylage',
    manufacturer: 'Vivacy',
    categories: ['Dermal Fillers', 'Bestsellers'],
    countryOfOrigin: 'France',
    description: 'Stylage Bi-Soft M Lidocaine is specifically designed to instantly correct medium to deep lines and wrinkles. Use it for nasolabial folds, sagging chin folds, marionette lines, nasal hump reduction or nasal tip lift, and hand rejuvenation including volume loss treatment on the back of the hands. Contains lidocaine for comfort.',
    packContents: ['2 x 1ml syringes', '2 x 30G ½" needles'],
    ingredients: ['20 mg/g cross-linked hyaluronic acid', '0.3% lidocaine'],
    benefits: ['Treats medium to deep wrinkles and lines', 'Corrects or reshapes nose and ears'],
    treatmentAreas: ['Face', 'Nasolabial folds', 'Marionette lines', 'Chin', 'Nose', 'Ears', 'Hand rejuvenation'],
    image: '/products/stylage-bi-soft-m-lidocaine.jpg',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'stylage-bi-soft-xl-1ml',
    name: 'Stylage Bi-Soft XL 1ml',
    brand: 'Stylage',
    manufacturer: 'Vivacy',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'France',
    description: 'Stylage Bi-Soft XL is an injectable hyaluronic acid volumizer specifically designed to restore facial volume lost over time. Recontouring the cheeks, cheekbones, chin, and jawline for a fuller, softer, more youthful appearance. Can also help treat skin sagging. Used in the deep dermis or subcutaneous layer.',
    packContents: ['2 x 1ml syringes'],
    ingredients: ['Hyaluronic acid', 'Mannitol'],
    benefits: ['Restore lost facial volume', 'Recontour facial features', 'Treatment of mild to severe skin sagging'],
    treatmentAreas: ['Cheeks', 'Cheekbones', 'Chin', 'Jawline'],
    image: '/products/stylage-bi-soft-xl-1ml.jpg',
    price: '€135',
    lidocaine: false,
    volume: '1ml',
  },
  {
    id: 'stylage-bi-soft-xxl',
    name: 'Stylage Bi-Soft XXL 2ml',
    brand: 'Stylage',
    manufacturer: 'Vivacy',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'France',
    description: 'Stylage Bi-Soft XXL is an injectable hyaluronic acid volumizer specifically designed to restore lost facial volume. Designed to treat mature skin showing signs of sagging and facial hollows. Used in subcutaneous tissue, recontouring cheeks, cheekbones, chin, and jawline for a fuller, softer, more youthful appearance.',
    packContents: ['2 x 1ml syringes', '1 x 25G 40mm cannula', '2 x 27G needle', '1 x 23G needle'],
    ingredients: ['21 mg/ml hyaluronic acid', 'Mannitol'],
    benefits: ['Restore lost facial volume', 'Recontour facial features', 'Treat sagging and facial hollows'],
    treatmentAreas: ['Cheeks', 'Cheekbones', 'Chin', 'Jawline'],
    image: '/products/stylage-bi-soft-xxl.jpg',
    price: '€150',
    lidocaine: false,
    volume: '2ml',
  },
  {
    id: 'stylage-m-1ml',
    name: 'Stylage M 1ml',
    brand: 'Stylage',
    manufacturer: 'Vivacy',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'France',
    description: 'Stylage M is specifically designed to correct moderate to deep lines and wrinkles while restoring natural facial volume and contours. For filling nasolabial folds, smoothing marionette lines, enhancing the chin and jawline, restoring facial harmony, and hand rejuvenation. Results are typically visible for 6–12 months.',
    packContents: ['2 x 1ml syringes'],
    ingredients: ['20 mg/ml hyaluronic acid', 'Mannitol'],
    benefits: ['Correction of moderate to deep wrinkles and folds', 'Helps restore facial volume and contours', 'Supports skin hydration and elasticity', 'Smooth consistency for ease of injection', 'Long-lasting formulation'],
    treatmentAreas: ['Face', 'Hand rejuvenation'],
    image: '/products/stylage-m-1ml.jpg',
    price: '€88',
    lidocaine: false,
    volume: '1ml',
  },
  {
    id: 'teosya-rha-2-lidocaine-1ml',
    name: 'Teosyal RHA 2 Lidocaine 1ml',
    brand: 'Teosyal',
    manufacturer: 'Teoxane',
    categories: ['Dermal Fillers', 'Lips'],
    countryOfOrigin: 'Switzerland',
    description: 'Teosyal RHA 2 Lidocaine is a dynamic dermal filler from the award-winning RHA® (Resilient Hyaluronic Acid) range, formulated to move naturally with facial expressions. Designed to treat moderate dynamic wrinkles and enhance lip contours. Soft, malleable gel with high stretch and moderate strength. Results typically last 12 to 18 months.',
    packContents: ['2 x 1ml syringes', '2 x 30G ½" needles'],
    ingredients: ['23 mg/ml hyaluronic acid (cross-linked HA)', '0.3% lidocaine', 'Degree of MoD (BDDE crosslinking): 3.1%'],
    benefits: ['Smooths moderate dynamic wrinkles', 'Enhance lip volume and contour', 'High stretch for flexible, natural movement', 'Suitable for upper and mid-face', 'Long-lasting: up to 12–18 months'],
    treatmentAreas: ['Forehead lines', 'Glabella', "Crow's feet", 'Nasolabial folds', 'Marionette lines', 'Perioral wrinkles', 'Lips including philtrum'],
    image: '/products/teosya-rha-2-lidocaine-1ml.jpg',
    price: '€135',
    lidocaine: true,
    volume: '1ml',
  },
  {
    id: 'teosyal-rha-4-lidocaine-1-2ml',
    name: 'Teosyal RHA 4 Lidocaine 1.2ml',
    brand: 'Teosyal',
    manufacturer: 'Teoxane',
    categories: ['Dermal Fillers'],
    countryOfOrigin: 'Switzerland',
    description: 'Teosyal RHA 4 Lidocaine is the thickest and most volumizing filler in the RHA® range, developed to restore structure and reshape contours in dynamic facial areas. Dense yet flexible gel ideal for cheeks, jawline, chin, and temples. Effective for deep nasolabial folds and marionette lines. Results last up to 18 months.',
    packContents: ['2 x 1.2ml syringes', '2 x 27G ½" needles'],
    ingredients: ['23 mg/ml hyaluronic acid (cross-linked HA)', '0.3% lidocaine', 'Degree of MoD (BDDE crosslinking): 4.1%'],
    benefits: ['Thick, flexible gel for high strength and natural movement', 'Smooths deep dynamic wrinkles', 'Enhances facial volume and contours', 'Adapts to facial movements for natural results', 'Long-lasting volume (up to 18 months)'],
    treatmentAreas: ['Temples', 'Cheeks', 'Chin', 'Jawline'],
    image: '/products/teosyal-rha-4-lidocaine-1-2ml.jpg',
    price: '€140',
    lidocaine: true,
    volume: '1.2ml',
  },
];

export function getProductsByCategory(category: string): Product[] {
  if (category === 'All') return products;
  return products.filter((p) => p.categories.includes(category));
}

export function getProductsByBrand(brand: string): Product[] {
  return products.filter((p) => p.brand === brand);
}

export function getBrands(): string[] {
  const seen: Record<string, boolean> = {};
  return products
    .map((p) => p.brand)
    .filter((b) => { if (seen[b]) return false; seen[b] = true; return true; })
    .sort();
}
